# Generated by Django 3.1.2 on 2026-05-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.TextField()),
                ('amount_group', models.IntegerField(default=1)),
                ('merchant_group', models.IntegerField(blank=True, null=True)),
                ('account_from_group', models.IntegerField(blank=True, null=True)),
                ('account_to_group', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finanzas.emailsource')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('classified', 'Classified'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('account_from', models.CharField(blank=True, max_length=100)),
                ('account_to', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.regexrule')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.emailsource')),
                ('tags', models.ManyToManyField(blank=True, to='finanzas.Tag')),
            ],
        ),
    ]
