# Generated by Django 3.1.2 on 2026-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexrule',
            name='date_format',
            field=models.CharField(blank=True, default='%d/%m/%Y', help_text='Use Python date format, e.g. %d/%m/%Y', max_length=50),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='date_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='time_format',
            field=models.CharField(blank=True, default='%H:%M', help_text='Use Python time format, e.g. %H:%M:%S', max_length=50),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='time_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('classified', 'Classified'), ('ignored', 'Ignored'), ('need_review', 'Need Review')], default='pending', max_length=20),
        ),
    ]
