# Generated by Django 3.1.2 on 2026-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20260504_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
