# Generated by Django 3.1.2 on 2026-05-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0003_tag_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexrule',
            name='remove_html_tags',
            field=models.BooleanField(default=True, help_text='If enabled, HTML tags will be removed from the email body before applying the regex.'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
