# Generated by Django 3.1.2 on 2020-11-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_entrada', models.CharField(max_length=200)),
                ('fecha_publicacion_entrada', models.DateTimeField(verbose_name='Fecha publicado')),
                ('texto_entrada', models.TextField()),
                ('visible_entrada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_comentario', models.CharField(max_length=255)),
                ('correo_autor_comentario', models.CharField(max_length=200)),
                ('fecha_publicacion_comentario', models.DateTimeField(verbose_name='Fecha publicado')),
                ('texto_comentario', models.TextField()),
                ('visible_comentario', models.BooleanField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.entrada')),
            ],
        ),
    ]
