# Generated by Django 3.1.2 on 2021-01-15 05:08

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha_edicion_entrada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha editado'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='imagen_entrada',
            field=models.FileField(blank=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tags_entrada',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_publicacion_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha publicado'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='texto_entrada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo_entrada',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='visible_entrada',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_entrada', models.CharField(blank=True, max_length=200)),
                ('fecha_publicacion_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha publicado')),
                ('fecha_edicion_entrada', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha editado')),
                ('imagen_entrada', models.FileField(blank=True, upload_to='imagenes/')),
                ('texto_entrada', models.TextField(blank=True, null=True)),
                ('tags_entrada', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
