# Generated by Django 3.1.2 on 2024-11-26 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha agregada')),
            ],
        ),
    ]
