# Generated by Django 3.1.2 on 2024-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('ON', 'Encendido'), ('OFF', 'Apagado')], max_length=3),
        ),
    ]
